// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfmQrpJ70sVnt4b3WJGfqEEQTnrKePio',
    appId: '1:1032660273237:web:45ec52ca0fe4d907c96cdc',
    messagingSenderId: '1032660273237',
    projectId: 'law-lens-3e24a',
    authDomain: 'law-lens-3e24a.firebaseapp.com',
    storageBucket: 'law-lens-3e24a.firebasestorage.app',
    measurementId: 'G-8R7N01TSVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6r86QVcF5Rh37n2Yo2TvXFB-F-9NO6f4',
    appId: '1:1032660273237:android:f107c1d82ff294c8c96cdc',
    messagingSenderId: '1032660273237',
    projectId: 'law-lens-3e24a',
    storageBucket: 'law-lens-3e24a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsx1gxdBvRLjAVd25ykKeif20pn4e2BhA',
    appId: '1:1032660273237:ios:095f80046473b09dc96cdc',
    messagingSenderId: '1032660273237',
    projectId: 'law-lens-3e24a',
    storageBucket: 'law-lens-3e24a.firebasestorage.app',
    iosClientId: '1032660273237-v8abdo9fmijdnv85g9tiavr3f4s4noto.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsx1gxdBvRLjAVd25ykKeif20pn4e2BhA',
    appId: '1:1032660273237:ios:095f80046473b09dc96cdc',
    messagingSenderId: '1032660273237',
    projectId: 'law-lens-3e24a',
    storageBucket: 'law-lens-3e24a.firebasestorage.app',
    iosClientId: '1032660273237-v8abdo9fmijdnv85g9tiavr3f4s4noto.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADfmQrpJ70sVnt4b3WJGfqEEQTnrKePio',
    appId: '1:1032660273237:web:32be871c026e33a3c96cdc',
    messagingSenderId: '1032660273237',
    projectId: 'law-lens-3e24a',
    authDomain: 'law-lens-3e24a.firebaseapp.com',
    storageBucket: 'law-lens-3e24a.firebasestorage.app',
    measurementId: 'G-4RF2JRQ25R',
  );
}
