name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle.kts') }}

      - name: Clean build
        working-directory: ./frontend
        run: flutter clean

      - name: Install Dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Build APK (Release)
        working-directory: ./frontend
        run: flutter build apk --release

      - name: Build AAB (Release)
        working-directory: ./frontend
        run: flutter build appbundle --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: law-lens-release-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 14

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: law-lens-release-aab
          path: frontend/build/app/outputs/bundle/release/app-release.aab
          retention-days: 14
